"""add start_date and end_date to subscriptions

Revision ID: d0e073ec1ccc
Revises: 744655f5622b
Create Date: 2025-05-29 16:23:55.504967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0e073ec1ccc'
down_revision: Union[str, None] = '744655f5622b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscriptions_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_payment_proofs_id'), table_name='payment_proofs')
    op.drop_index(op.f('ix_payment_proofs_user_id'), table_name='payment_proofs')
    op.drop_table('payment_proofs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_proofs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('course_id', sa.VARCHAR(), nullable=False),
    sa.Column('file_id', sa.VARCHAR(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_proofs_user_id'), 'payment_proofs', ['user_id'], unique=False)
    op.create_index(op.f('ix_payment_proofs_id'), 'payment_proofs', ['id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('course_id', sa.VARCHAR(), nullable=False),
    sa.Column('start', sa.DATETIME(), nullable=True),
    sa.Column('end', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_id'), 'subscriptions', ['id'], unique=False)
    # ### end Alembic commands ###
